include ../Makefile

targets:	Assignment2.pdf
zips:		template.zip

template.zip:	run_solution.py solution.py
	zip $@ $^

deploy:
	@echo Upload files: Assignment1.pdf template.zip solution.py run_solution.py
