include ../Makefile

targets:	Assignment2.pdf
zips:		template-assignment-2.zip

template-assignment-2.zip:	run_solution.py solution.py
	zip $@ $^

deploy:
	@echo Upload files: Assignment1.pdf template-assignment-2.zip
